### ISSUE TITLE
Helm chart not uninstalling custom resources

### ISSUE THREAD

**Issue by awcheney** [fluent/fluentbit-operator#132]
I've been installing the operator using terraform to install using your helm chart and I'm finding some problems running a `terraform destroy` - it eventually times out because it can't delete the namespace. This seems to be due to the `fluentbits` custom resource finalizer - if I patch the resource to remove the finalizer, the deletion proceeds as expected.

To take terraform out of the equation, I created the namespace by hand and then ran a `helm install`, using the same values, followed by `helm uninstall` - this deleted the operator pod but not the daemonset, nor the `fluentbits` custom resource. The helm release *is* deleted, though, so cleanup is to delete the namespace, then patch the `fluentbits` resource again.

**Comment by wenchajun** [comment]
Helm does not remove resources such as CRD
> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

And fluentbit is not deployed by helm, it is generated by Fluentbit-Operator.

**Comment by awcheney** [comment]
Aaaah, OK, of course - d'oh! Thanks @wenchajun...
