### ISSUE TITLE
How can I add log file path into log record?

### ISSUE THREAD

**Issue by LQBing** [fluent/fluentbit-operator#159]
Some different log file in my log folder, I wanna know which one log file the log record collected from.

**Comment by wenchajun** [comment]
It collects file paths in /var/log 、/var/log/journal   etc 。You can refer to this
https://github.com/fluent/fluentbit-operator/blob/master/pkg/operator/daemonset.go#L137

**Comment by LQBing** [comment]
> It collects file paths in /var/log 、/var/log/journal etc .You can refer to this https://github.com/fluent/fluentbit-operator/blob/master/pkg/operator/daemonset.go#L137

First, thx for your reply :)

I don’t know if it’s my presentation problem. I wanna add a field and fill it with the log file path into the log record, to let our dev know which one log file the log record collected from.
I'm trying migrate our log collect system from logstash + filebeat to fluentbit, but the `source` field is very importent for us. I searched your documents, and not find any param to set log file path into log record.
Is there any way to get that? Like the `source` field in logstash.

**Comment by wanjunlei** [comment]
According to your description, you should use `Tail` to collect logs. The `tail` can add the absolute path of the log file to the `tag`, 

<img width="412" alt="1635735948(1)" src="https://user-images.githubusercontent.com/53003665/139616206-43beac52-96b9-4489-b703-e5fce98231f4.png">

https://docs.fluentbit.io/manual/pipeline/inputs/tail

and then you can use a `lua` filter to get the path of the log file and add it to the record.

https://docs.fluentbit.io/manual/pipeline/filters/lua

**Comment by benjaminhuo** [comment]
@LQBing Not sure if you're collecting logs in k8s env. K8s pod logs are output to the stdout and thus don't have a path, the k8s metadata like namespace, pod, container are all collected as part of the log messages, so if you're using fluentbit operator to collect k8s pod logs, you'll already have the info about where the log message comes from（from which namespace, pod, and container.

If you're collecting non-k8s logs, you can use fluentbit directly (no need to install fluentbit operator) and use the method @wanjunlei mentioned to add file path the the log

**Comment by LQBing** [comment]
I find it, `pathKey` in `tail` plugin.

I'm sorry for waste your time and very thanks for your help. @wenchajun @wanjunlei  & @benjaminhuo

**Comment by LQBing** [comment]
> According to your description, you should use `Tail` to collect logs. The `tail` can add the absolute path of the log file to the `tag`,
> 
> <img alt="1635735948(1)" width="412" src="https://user-images.githubusercontent.com/53003665/139616206-43beac52-96b9-4489-b703-e5fce98231f4.png">
> 
> https://docs.fluentbit.io/manual/pipeline/inputs/tail
> 
> and then you can use a `lua` filter to get the path of the log file and add it to the record.
> 
> https://docs.fluentbit.io/manual/pipeline/filters/lua

How to add my lua script? 
I find `fluent-bit` pod load secret `fluent-bit-config` in namespace `kubesphere-logging-system`. I modified it, but it filled back after inputs.logging.kubesphere.io update.
I modified configmap `fluent-bit-lua` in namespace `kubesphere-logging-system`, but it doesn't seem to work.

**Comment by wenchajun** [comment]
The operator watches those objects, constructs the final config, and finally creates a Secret to store the config. This secret will be mounted into the Fluent Bit DaemonSet.https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/filter/lua_types.go,https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml

**Comment by LQBing** [comment]
> The fluentbit-operator watches those objects, constructs the final config, and finally creates a Secret to store the config. This secret will be mounted into the Fluent Bit DaemonSet.For details, refer to https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/filter/lua_types.go, https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml

I see. I added a test lua into the configmap, template from https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml . But the created Secret is not include my test lua script.

kubesphere version : v3.1.1
fluentbit-operator Image: kubesphere/fluentbit-operator:v0.5.0
fluent-bit Image: kubesphere/fluent-bit:v1.6.9

![image](https://user-images.githubusercontent.com/6857508/139640787-31787aa5-f564-4317-b2f9-af01bf724d27.png)
![image](https://user-images.githubusercontent.com/6857508/139640869-fd505cbe-8675-4bf7-8515-6d37234ad2de.png)

**Comment by wenchajun** [comment]
> > The fluentbit-operator watches those objects, constructs the final config, and finally creates a Secret to store the config. This secret will be mounted into the Fluent Bit DaemonSet.For details, refer to https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/filter/lua_types.go, https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml
> 
> I see. I added a test lua into the configmap, template from https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml . But the created Secret is not include my test lua script.
> 
> kubesphere version : v3.1.1 fluentbit-operator Image: kubesphere/fluentbit-operator:v0.5.0 fluent-bit Image: kubesphere/fluent-bit:v1.6.9
> 
> ![image](https://user-images.githubusercontent.com/6857508/139640787-31787aa5-f564-4317-b2f9-af01bf724d27.png) ![image](https://user-images.githubusercontent.com/6857508/139640869-fd505cbe-8675-4bf7-8515-6d37234ad2de.png)

Have you configured the corresponding filter？ like this
https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-systemd.yaml

**Comment by LQBing** [comment]
> > > The fluentbit-operator watches those objects, constructs the final config, and finally creates a Secret to store the config. This secret will be mounted into the Fluent Bit DaemonSet.For details, refer to https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/filter/lua_types.go, https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml
> > 
> > 
> > I see. I added a test lua into the configmap, template from https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/systemd-lua-config.yaml . But the created Secret is not include my test lua script.
> > kubesphere version : v3.1.1 fluentbit-operator Image: kubesphere/fluentbit-operator:v0.5.0 fluent-bit Image: kubesphere/fluent-bit:v1.6.9
> > ![image](https://user-images.githubusercontent.com/6857508/139640787-31787aa5-f564-4317-b2f9-af01bf724d27.png) ![image](https://user-images.githubusercontent.com/6857508/139640869-fd505cbe-8675-4bf7-8515-6d37234ad2de.png)
> 
> Have you configured the corresponding filter？ like this https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-systemd.yaml

You mean the custom lua script will be write into the Secret only the lua script is called by someone?

**Comment by wenchajun** [comment]
Fluentbit configuration is written by operator. You can refer to lua configuration  https://docs.fluentbit.io/manual/pipeline/filters/lua

**Comment by LQBing** [comment]
> Fluentbit configuration is written by operator. You can refer to lua configuration https://docs.fluentbit.io/manual/pipeline/filters/lua

It works! Thank you!
