### ISSUE TITLE
TimeKeep param in plugins/parser/regex_types.go incorrect

### ISSUE THREAD

**Issue by LQBing** [fluent/fluentbit-operator#163]
https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/parser/regex_types.go

```go
	if re.TimeKeep != nil {
		kvs.Insert("Time_Format", fmt.Sprint(*re.TimeKeep))
	}
```
It's incorrect! It is not `Time_Format true`

I find the time `Time_Keep` value `Time_Keep   On`  from fluent default parsers.conf

![image](https://user-images.githubusercontent.com/6857508/139824579-10c156a8-5d1a-45cb-928d-1b6dac9d9e2d.png)

**Comment by wenchajun** [comment]
Maybe Time_Keep is better

**Comment by wanjunlei** [comment]
> https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/parser/regex_types.go
> 
> ```go
> 	if re.TimeKeep != nil {
> 		kvs.Insert("Time_Format", fmt.Sprint(*re.TimeKeep))
> 	}
> ```
> 
> It's incorrect! It is not `Time_Format true`
> 
> I find the time `Time_Keep` value `Time_Keep On` from fluent default parsers.conf
> 
> ![image](https://user-images.githubusercontent.com/6857508/139824579-10c156a8-5d1a-45cb-928d-1b6dac9d9e2d.png)

Thank you for this, do you want to commit a PR to resolve this bug?

In addition, fluent bit is written in C language, in C language, `on` and `true` all will be converted to `1`, so `Time_Keep on` and `Time_Keep true` are both correct.

**Comment by LQBing** [comment]
> > https://github.com/fluent/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/parser/regex_types.go
> > ```go
> > 	if re.TimeKeep != nil {
> > 		kvs.Insert("Time_Format", fmt.Sprint(*re.TimeKeep))
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's incorrect! It is not `Time_Format true`
> > I find the time `Time_Keep` value `Time_Keep On` from fluent default parsers.conf
> > ![image](https://user-images.githubusercontent.com/6857508/139824579-10c156a8-5d1a-45cb-928d-1b6dac9d9e2d.png)
> 
> Thank you for this, do you want to commit a PR to resolve this bug?
> 
> In addition, fluent bit is written in C language, in C language, `on` and `true` all will be converted to `1`, so `Time_Keep on` and `Time_Keep true` are both correct.

I committed the PR. But I'm not sure is there anything missing.

https://github.com/fluent/fluentbit-operator/pull/164
