### ISSUE TITLE
Fluentbit-operator doesn't reload configuration

### ISSUE THREAD

**Issue by satrushn** [fluent/fluentbit-operator#168]
Hello. 

I installed fluentbit-operator and it works. When I tried to configure something, change parsing, output, etc.
And I don't understand how it must reload changings. 
I tried to restart pods but it doesn't help. Then in two hours I recognized that my new configuration installed. 
But I don't understand how it works, how much time I must wait and which parameter I must adjust to reload it more often

Help me please.
Thanks.

**Comment by wenchajun** [comment]
Normally, the fluentbit-Operator automatically updates the configuration after you update the corresponding CRD. You can check the secret `fluent-bit-config` after the update. If it is changed, it means that the configuration is updated successfully

**Comment by satrushn** [comment]
Thank you for your answer. It helped me to find what happened.
