### ISSUE TITLE
Invalid modification of ExcludePath

### ISSUE THREAD

**Issue by bigfacewo** [fluent/fluentbit-operator#169]
I use fluent bit on kubesphere. Theoretically, I can determine which logs will be collected by modifying "input.spec.tail.excludepath", but I find it useless. I failed to ask for help in kubesphere forum. [This is the kubesphere forum link.](https://kubesphere.com.cn/forum/d/6073-kube-system)

fluent-bit:v1.6.9

Thank you very much for any help

**Comment by wenchajun** [comment]
Thanks，I looked at the link. Please note the `Pod` fields in the picture. In other words, the log on the image is not the log generated on the POD. It is the log generated by the node. In fact, the log under the path has been excluded. As for why this log is generated, it is generated by docker and kubelet files.

**Comment by bigfacewo** [comment]
@wenchajun Thanks,I'll see how to exclude these logs.
