### ISSUE TITLE
[discussion]Do we need to change the domain?

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluentbit-operator#171]
Although the CRD is currently at the namespace level, cluster-level logs and information can be collected. Wouldn't it make sense to add cluster-level CRDS? Because at the user level, usage is indistinguishable. What do we need to change? Domain? Or the name?

**Comment by benjaminhuo** [comment]
We need cluster level crds because collecting logs is a cluster-wide behavior, we use namespace crd is not correct.  Namespaced crd should only collect namespace level logs.

**Comment by benjaminhuo** [comment]
Now fb operator is a community project. Currently, it works doesn't mean the project should be kept that way.

**Comment by wenchajun** [comment]
Perhaps namespace-level CRDS will be obsolete in the future? However, in prometheus-operator crds, it is also namespace level

**Comment by benjaminhuo** [comment]
Ref

> Perhaps namespace-level CRDS will be obsolete in the future? However, in prometheus-operator crds, it is also namespace level

https://banzaicloud.com/docs/one-eye/logging-operator/ is a good example and prometheus is not

**Comment by wenchajun** [comment]
If so, maybe this PR is better https://github.com/fluent/fluentbit-operator/pull/167. 

> > Perhaps namespace-level CRDS will be obsolete in the future? However, in prometheus-operator crds, it is also namespace level
> 
> https://banzaicloud.com/docs/one-eye/logging-operator/ is a good example and prometheus is not Namespaced CRDs should be changed to the new fluentbit.fluent.io domain and it should be restricted to process logs of that namespace Keeping the original CRDs in kubesphere.io is for backward compatibility
