### ISSUE TITLE
kafka output not support dynamic_topic configuration

### ISSUE THREAD

**Issue by inversionhourglass** [fluent/fluentbit-operator#177]
fluentbit supports `Dynamic_Topic` starting with version [1.5](https://docs.fluentbit.io/manual/v/1.5/pipeline/outputs/kafka), but I can find this configuration key in [API Doc](https://github.com/fluent/fluentbit-operator/blob/release-0.12/docs/plugins/output/kafka.md)

**Comment by wenchajun** [comment]
Yes, I will add corresponding support later, if you like, you can provide corresponding PR
