### ISSUE TITLE
level=error err="no such file or directory" when trying to add config files to /fluent-bit/etc

### ISSUE THREAD

**Issue by LeonD9** [fluent/fluentbit-operator#188]
Hey,
I am using the following image `kubespheredev/fluent-bit:v1.8.11` and trying to create /etc/fluent-bit/config directory to store config files i gather through sidecar in there (tried creating config files that are not fluent-bit.conf or parsers.conf in there and it doesn't work either)
and use via `@INCLUDE` method in main fluent-bit config since its not possible to include files that aren't in `fluent-bit/etc` directory.

Is there something i am missing? how can i add config files that will reload dynamically in `kubespheredev/fluent-bit:v1.8.11` image?

**Comment by wanjunlei** [comment]
By default, adding config files that are not `fluent-bit.conf` or `parsers.conf` is not supported.

https://github.com/fluent/fluentbit-operator/blob/master/conf/fluent-bit.conf#L1


If you want to do this, you can modify the `fluent-bit.conf` file and build a new image

https://github.com/fluent/fluentbit-operator/blob/master/Makefile#L81
